### ISSUE TITLE
wrong stylesheet.css file name in index.html 

### ISSUE THREAD

**Issue by JDpawar** [Ganpatkakar/Custom-Tabs-Accordion#1]
The name of the css file should be **stylesheet.css** instead of stylesheets.css in the index.html

**Comment by Ganpatkakar** [comment]
Thank you JDpawar, 
I have resolved this issue.
I ll recommend you my new repository chartjs ( https://github.com/Ganpatkakar/Chartjs )
Please check and give your feedback.

Thank you

**Comment by JDpawar** [comment]
I was about to tell you for the CDN links. :)

## 

Thanks and regards

JD Pawar
Software Engineer
Mob: +91 7276 89 4525

Facebook https://www.facebook.com/JDpawar Linkedin
https://www.linkedin.com/pub/jd-pawar/8a/914/561 Twitter
https://twitter.com/JDpawar

**Comment by Ganpatkakar** [comment]
And i have added them first.
